### ISSUE TITLE
Error: NaN is less than min_coverage 95 - Unexpected NaN coverage value

### ISSUE THREAD

**Issue by Archie-Elvie** [VeryGoodOpenSource/very_good_coverage#146] opened 2022-05-31 19:18 UTC
**Describe the bug**
While running the action it reports NaN coverage, while lcov it self reports 100%.

```
Reading tracefile code-coverage/lcov.info
            |Lines       |Functions  |Branches    
Filename    |Rate     Num|Rate    Num|Rate     Num
==================================================
[/workspaces/project/src/]
bar.cpp     | 100%      4| 100%     2|    -      0
==================================================
      Total:| 100%      4| 100%     2|    -      0
```

**To Reproduce**
Steps to reproduce the behaviour:

Use the following lcov.info

lcov.info
```
TN:
SF:/__w/project/project/src/bar.cpp
FN:3,_Z8set_gpioPK6devicehi
FNDA:2,_Z8set_gpioPK6devicehi
FN:8,_Z3addii
FNDA:2,_Z3addii
DA:3,2
DA:5,2
DA:8,2
DA:10,2
end_of_record
```

**Expected behavior**
It reports 100% and passes

**Screenshots**
None

**Additional context**
None

Let me know if you need more information.

**Comment by alestiago** [comment] 2023-03-07 13:30
Thanks for the issue @Archie-Elvie , sorry for the late reply. Is this still an issue?

**Comment by Archie-Elvie** [comment] 2023-03-09 14:41
Yeah I still get NaN whenever I try and use it

**Comment by alestiago** [comment] 2023-03-15 19:56
I've been able to reproduce this issue on v2.1.0. 

A sample can be found [here](https://github.com/alestiago/issues/tree/very_good_coverage-146-20230315) and a pull request with the action failing [here](https://github.com/alestiago/issues/pull/3).

**Comment by alestiago** [comment] 2023-03-16 12:23
@Archie-Elvie by any chance do you have a reference to the exact tool you're using to generate the lcov file and the tool you'r using to report the lcov file result?

**Comment by renancaraujo** [comment] 2023-05-02 12:29
It seems like this is an invalid lcov file, at least from the [parser](https://github.com/davglass/lcov-parse/blob/master/lib/index.js#L30) standpoint. There is no data on found/hit for functions and lines, which we use for calculating code coverage. 


Closing as a `wontfix` since there is not much we can do here in this case with the info we have.

**Closed as completed by renancaraujo** 2023-05-02 12:29 UTC
Labels: won't fix
